### ISSUE TITLE
AWS Agent Setup Instructions have broken image link

### ISSUE THREAD

**Issue by alanc10n** [dockup/docs#5]
https://github.com/dockup/docs/blob/master/selfhosting/setup-agent-aws.md describes how to set up the self-hosted agent, but it has an embedded image link that's broken: https://github.com/dockup/docs/blob/master/images/aws_kubernetes_create.png.

**Comment by iffyuva** [comment]
Hi @alanc10n . Thanks for pointing it out. Fix on the way :)
